---
name: "{{global['github']['repository']}}"
version: "{{major}}.{{minor}}.{{patch}}"
description: "A real-time telemetry library."
entry: "{{global['github']['repository']}}"
requirements:
  - cerberus
  - netifaces
  - requests
  - websockets
  - vcorelib
dev_requirements:
  - setuptools-wrapper
init_local: |
  DEFAULT_TIMEOUT = 2
mypy_local: |
  [mypy-cerberus.*]
  ignore_missing_imports = True

  [mypy-netifaces.*]
  ignore_missing_imports = True
