---
name: "{{global['github']['repository']}}"
version: "{{major}}.{{minor}}.{{patch}}"
description: "A real-time telemetry library."
entry: "{{global['github']['repository']}}"
requirements:
  - cerberus
  - datazen
  - netifaces
  - requests
  - websockets
  - vcorelib
dev_requirements:
  - setuptools-wrapper
