# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - uses: textbook/git-checkout-submodule-action@master
    - name: python${{matrix.python-version}} setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-mk
      run: |
        pip${{matrix.python-version}} install vmklib
    - name: venv
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} venv
    - name: lint
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} python-lint
    - name: sa-types
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} python-sa-types
    - name: sa
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} python-sa
    - name: test
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} python-test
    - name: dist
      run: |
        mk PYTHON_VERSION=${{matrix.python-version}} python-dist
